<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Student;
use App\Models\ClassModel;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class ParentsWithChildrenSeeder extends Seeder
{
    public function run(): void
    {
        // Create Parent Role if not exists
        Role::firstOrCreate(['name' => 'parent']);

        // Define grade levels with their specific sections
        // You can modify this array to control which grade levels exist and their sections
        $gradeSections = [
            // 'K1' => ['Gold', 'Silver'],
            // 'K2' => ['Diamond', 'Emerald'],
            '1'  => ['St. Catherine', 'St. Michael', 'St. Joseph'],
            '2'  => ['St. Prisca'],             
            '3'  => ['St. John', 'St. Luke'],
            '4'  => ['St. Anthony'],
            '5'  => ['St. Benedict'],
            // '6'  => ['Pearl', 'Crystal'],
        ];

        // Create Classes for each grade level with their specific sections
        foreach ($gradeSections as $gradeLevel => $sections) {
            foreach ($sections as $section) {
                ClassModel::firstOrCreate([
                    'grade_level' => $gradeLevel,
                    'name' => $section,
                    'teacher_id' => null,
                ]);
            }
        }

        // Display created classes for reference
        $this->command->info("Created Classes:");
        foreach ($gradeSections as $gradeLevel => $sections) {
            $this->command->info("Grade {$gradeLevel}: " . implode(', ', $sections));
        }

        // ACTUAL STUDENT DATA - You can modify this array with real student information
        $studentsData = [

                /////////////////////////////////////////////////////////////////////////////////////
                // St. Catherine
                [
                    'first_name' => 'Chyster Klent',
                    'middle_name' => 'I',
                    'last_name' => 'Alibo',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Male',
                    'lrn' => '000000000001',
                ],
                [
                    'first_name' => 'Morgan',
                    'middle_name' => 'A',
                    'last_name' => 'Dean',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Male',
                    'lrn' => '000000000002',
                ],
                [
                    'first_name' => 'Roshan Dave',
                    'middle_name' => 'M',
                    'last_name' => 'Galacio',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Male',
                    'lrn' => '000000000003',
                ],
                [
                    'first_name' => 'Stephen Ryann',
                    'middle_name' => 'D',
                    'last_name' => 'Gimena',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Male',
                    'lrn' => '000000000004',
                ],
                [
                    'first_name' => 'Eri Zander',
                    'middle_name' => 'E',
                    'last_name' => 'Hermoso',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Male',
                    'lrn' => '000000000005',
                ],
                [
                    'first_name' => 'Zian Xavier',
                    'middle_name' => 'R',
                    'last_name' => 'Mapute',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Male',
                    'lrn' => '000000000006',
                ],
                [
                    'first_name' => 'Gabriel Eiden',
                    'middle_name' => 'F',
                    'last_name' => 'Remoreras',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Male',
                    'lrn' => '000000000007',
                ],
                [
                    'first_name' => 'Justin',
                    'middle_name' => 'T',
                    'last_name' => 'Stolz',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Male',
                    'lrn' => '000000000008',
                ],
                [
                    'first_name' => 'Niña Angelica',
                    'middle_name' => 'B',
                    'last_name' => 'Ahora',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000009',
                ],
                [
                    'first_name' => 'Ma. Julia Stephanie',
                    'middle_name' => 'A',
                    'last_name' => 'Bancale',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000010',
                ],
                [
                    'first_name' => 'Princess Jennelé',
                    'middle_name' => 'B',
                    'last_name' => 'Celis',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000011',
                ],
                [
                    'first_name' => 'Kaylie',
                    'middle_name' => 'R',
                    'last_name' => 'Cuizon',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000012',
                ],
                [
                    'first_name' => 'Sapphire',
                    'middle_name' => 'F',
                    'last_name' => 'Infiesto',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000013',
                ],
                [
                    'first_name' => 'Jasmine',
                    'middle_name' => 'P',
                    'last_name' => 'Milar',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000014',
                ],
                [
                    'first_name' => 'Niña Gabriella',
                    'middle_name' => '',
                    'last_name' => 'Nazareno',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000015',
                ],
                [
                    'first_name' => 'Diana Lei',
                    'middle_name' => 'P',
                    'last_name' => 'Ramientos',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000016',
                ],
                [
                    'first_name' => 'Zekainah Phillys',
                    'middle_name' => 'C',
                    'last_name' => 'Revilla',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000017',
                ],
                [
                    'first_name' => 'Amira',
                    'middle_name' => 'N',
                    'last_name' => 'Saif',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000018',
                ],
                [
                    'first_name' => 'Jyll Scarlette',
                    'middle_name' => 'T',
                    'last_name' => 'Soliano',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000019',
                ],
                [
                    'first_name' => 'Mary Livinn',
                    'middle_name' => 'P',
                    'last_name' => 'Tumabang',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000020',
                ],
                [
                    'first_name' => 'Hailey',
                    'middle_name' => 'M',
                    'last_name' => 'Vistal',
                    'grade_level' => '1',
                    'section' => 'St. Catherine',
                    'gender' => 'Female',
                    'lrn' => '000000000021',
                ],
                
                /////////////////////////////////////////////////////////////////////////////////////
                // St. Prisca
                [
                    'first_name' => 'Davin Niyjah',
                    'middle_name' => '',
                    'last_name' => 'Asubar',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Male',
                    'lrn' => '000000000022',
                ],
                [
                    'first_name' => 'Jumarie',
                    'middle_name' => 'Y',
                    'last_name' => 'Basilisco',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Male',
                    'lrn' => '000000000023',
                ],
                [
                    'first_name' => 'Zach Ethan',
                    'middle_name' => 'Q',
                    'last_name' => 'Cenabre',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Male',
                    'lrn' => '000000000024',
                ],
                [
                    'first_name' => 'Vinz Sanjay',
                    'middle_name' => 'C',
                    'last_name' => 'Estose',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Male',
                    'lrn' => '000000000025',
                ],
                [
                    'first_name' => 'Cecilio',
                    'middle_name' => '',
                    'last_name' => 'Itable',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Male',
                    'lrn' => '000000000026',
                ],
                [
                    'first_name' => 'Ethan Jude',
                    'middle_name' => 'C',
                    'last_name' => 'Mariveles',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Male',
                    'lrn' => '000000000027',
                ],
                [
                    'first_name' => 'Jeziah David',
                    'middle_name' => 'A',
                    'last_name' => 'Oliamot',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Male',
                    'lrn' => '000000000028',
                ],
                [
                    'first_name' => 'Chaison Rooji',
                    'middle_name' => '',
                    'last_name' => 'Ricopuerto',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Male',
                    'lrn' => '000000000029',
                ],
                [
                    'first_name' => 'Alphonso',
                    'middle_name' => 'G',
                    'last_name' => 'Toyugan',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Male',
                    'lrn' => '000000000030',
                ],
                [
                    'first_name' => 'Preia',
                    'middle_name' => 'A',
                    'last_name' => 'Aparre',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Female',
                    'lrn' => '000000000031',
                ],
                [
                    'first_name' => 'Athena Chloe',
                    'middle_name' => 'L',
                    'last_name' => 'Calunia',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Female',
                    'lrn' => '000000000032',
                ],
                [
                    'first_name' => 'Pasciela Crysten',
                    'middle_name' => 'N',
                    'last_name' => 'Gallego',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Female',
                    'lrn' => '000000000033',
                ],
                [
                    'first_name' => 'Zidbelle',
                    'middle_name' => 'A',
                    'last_name' => 'Garcia',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Female',
                    'lrn' => '000000000034',
                ],
                [
                    'first_name' => 'Liza Amore',
                    'middle_name' => 'M',
                    'last_name' => 'Lupague',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Female',
                    'lrn' => '000000000035',
                ],
                [
                    'first_name' => 'Zaliyah',
                    'middle_name' => 'D',
                    'last_name' => 'Mamanao',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Female',
                    'lrn' => '000000000036',
                ],
                [
                    'first_name' => 'Kalleen Faith',
                    'middle_name' => 'R',
                    'last_name' => 'Morgado',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Female',
                    'lrn' => '000000000037',
                ],
                [
                    'first_name' => 'Jade Sofia',
                    'middle_name' => 'A',
                    'last_name' => 'Tortor',
                    'grade_level' => '2',
                    'section' => 'St. Prisca',
                    'gender' => 'Female',
                    'lrn' => '000000000038',
                ],

                /////////////////////////////////////////////////////////////////////////////////////
                // St. John
                [
                    'first_name' => 'Johann Gadiel',
                    'middle_name' => 'D',
                    'last_name' => 'Amodia',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000039',
                ],
                [
                    'first_name' => 'Amadeus Mikhael',
                    'middle_name' => 'A',
                    'last_name' => 'Anosa',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000040',
                ],
                [
                    'first_name' => 'James Jopher',
                    'middle_name' => 'B',
                    'last_name' => 'Baquilo',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000041',
                ],
                [
                    'first_name' => 'Erick Johann',
                    'middle_name' => 'R',
                    'last_name' => 'Caliao',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000042',
                ],
                [
                    'first_name' => 'Earlyle Aries',
                    'middle_name' => 'A',
                    'last_name' => 'Duhaylungsod',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000043',
                ],
                [
                    'first_name' => 'Blake Nathan',
                    'middle_name' => 'A',
                    'last_name' => 'Fuentes',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000044',
                ],
                [
                    'first_name' => 'Rhylle Matthew',
                    'middle_name' => 'A',
                    'last_name' => 'Lumayag',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000045',
                ],
                [
                    'first_name' => 'Giovanni Liam',
                    'middle_name' => 'A',
                    'last_name' => 'Metz',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000046',
                ],
                [
                    'first_name' => 'Dale',
                    'middle_name' => 'M',
                    'last_name' => 'Opelinia',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000047',
                ],
                [
                    'first_name' => 'Kyle Devmer',
                    'middle_name' => '',
                    'last_name' => 'Pino',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000048',
                ],
                [
                    'first_name' => 'Benjamen Angelo',
                    'middle_name' => '',
                    'last_name' => 'Raciti',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000049',
                ],
                [
                    'first_name' => 'Dylan Jay',
                    'middle_name' => 'P',
                    'last_name' => 'Ramientos',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000050',
                ],
                [
                    'first_name' => 'Lord Ethan Zyke',
                    'middle_name' => 'B',
                    'last_name' => 'Rayas',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Male',
                    'lrn' => '000000000051',
                ],
                [
                    'first_name' => 'Shazny Ann',
                    'middle_name' => 'G',
                    'last_name' => 'Astronomo',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000052',
                ],
                [
                    'first_name' => 'Phoebe Kate',
                    'middle_name' => 'A',
                    'last_name' => 'Bancale',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000053',
                ],
                [
                    'first_name' => 'Gabriel Anne',
                    'middle_name' => 'M',
                    'last_name' => 'Chen',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000054',
                ],
                [
                    'first_name' => 'Cerys Lexi',
                    'middle_name' => 'D',
                    'last_name' => 'Cording',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000055',
                ],
                [
                    'first_name' => 'Mary Bless Ellaine',
                    'middle_name' => 'H',
                    'last_name' => 'Dungog',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000056',
                ],
                [
                    'first_name' => 'Katlyn Emmarie',
                    'middle_name' => 'P',
                    'last_name' => 'Gastones',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000057',
                ],
                [
                    'first_name' => 'Khassie Dee',
                    'middle_name' => 'V',
                    'last_name' => 'Gulayan',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000058',
                ],
                [
                    'first_name' => 'Mia Athena',
                    'middle_name' => 'M',
                    'last_name' => 'Gullat',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000059',
                ],
                [
                    'first_name' => 'Cresh Jianeshia',
                    'middle_name' => 'S',
                    'last_name' => 'Jumamid',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000060',
                ],
                [
                    'first_name' => 'Eachna',
                    'middle_name' => 'G',
                    'last_name' => 'Longridge',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000061',
                ],
                [
                    'first_name' => 'Mei Jerikah',
                    'middle_name' => 'M',
                    'last_name' => 'Man-On',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000062',
                ],
                [
                    'first_name' => 'Lady Arabella',
                    'middle_name' => 'B',
                    'last_name' => 'Mata',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000063',
                ],
                [
                    'first_name' => 'Rhyn Lian',
                    'middle_name' => 'C',
                    'last_name' => 'Miel',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000064',
                ],
                [
                    'first_name' => 'Crisha Mary',
                    'middle_name' => 'P',
                    'last_name' => 'Milar',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000065',
                ],
                [
                    'first_name' => 'Zephaniah Jesheil',
                    'middle_name' => 'A',
                    'last_name' => 'Monte De Ramos',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000066',
                ],
                [
                    'first_name' => 'Jannah Raine',
                    'middle_name' => 'C',
                    'last_name' => 'Nioda',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000067',
                ],
                [
                    'first_name' => 'Zephirah Alika',
                    'middle_name' => 'B',
                    'last_name' => 'Ohina',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000068',
                ],
                [
                    'first_name' => 'Jilliane',
                    'middle_name' => 'F',
                    'last_name' => 'Remoreras',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000069',
                ],
                [
                    'first_name' => 'Nathalia Zayne',
                    'middle_name' => 'V',
                    'last_name' => 'Ruizo',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000070',
                ],
                [
                    'first_name' => 'Tatiana Xiamarrah',
                    'middle_name' => 'M',
                    'last_name' => 'Tanic',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000071',
                ],
                [
                    'first_name' => 'Princess Marthela Eona',
                    'middle_name' => 'M',
                    'last_name' => 'Vano',
                    'grade_level' => '3',
                    'section' => 'St. John',
                    'gender' => 'Female',
                    'lrn' => '000000000072',
                ],

                /////////////////////////////////////////////////////////////////////////////////////
                // St. Michael
                [
                    'first_name' => 'Carl Albrecht Fabiolas',
                    'middle_name' => '',
                    'last_name' => 'Cajes',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Male',
                    'lrn' => '000000000073',
                ],
                [
                    'first_name' => 'Mark Zane',
                    'middle_name' => 'Toquib',
                    'last_name' => 'Ediza',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Male',
                    'lrn' => '000000000074',
                ],
                [
                    'first_name' => 'Jared Laurent Zoilo',
                    'middle_name' => '',
                    'last_name' => 'Errojo',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Male',
                    'lrn' => '000000000075',
                ],
                [
                    'first_name' => 'Zander Nicolas Suarez',
                    'middle_name' => '',
                    'last_name' => 'Falcon',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Male',
                    'lrn' => '000000000076',
                ],
                [
                    'first_name' => 'Shadrach',
                    'middle_name' => 'Singcol',
                    'last_name' => 'Gacera',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Male',
                    'lrn' => '000000000077',
                ],
                [
                    'first_name' => 'Eliseo Markus',
                    'middle_name' => 'Salubre',
                    'last_name' => 'Mediano',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Male',
                    'lrn' => '000000000078',
                ],
                [
                    'first_name' => 'Zachary Rafael',
                    'middle_name' => 'Patac',
                    'last_name' => 'Omus',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Male',
                    'lrn' => '000000000079',
                ],
                [
                    'first_name' => 'Quinn Axl',
                    'middle_name' => '',
                    'last_name' => 'Suaybaguio',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Male',
                    'lrn' => '000000000080',
                ],
                [
                    'first_name' => 'Jurel Adam',
                    'middle_name' => 'Torrefranca',
                    'last_name' => 'Tunacao',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Male',
                    'lrn' => '000000000081',
                ],
                [
                    'first_name' => 'Zacharie Lyrah',
                    'middle_name' => 'Guadez',
                    'last_name' => 'Bamba',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000082',
                ],
                [
                    'first_name' => 'Khloe Claire',
                    'middle_name' => 'Guibay',
                    'last_name' => 'Canono',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000083',
                ],
                [
                    'first_name' => 'Blythe Anika',
                    'middle_name' => 'Alo',
                    'last_name' => 'Dela Cruz',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000084',
                ],
                [
                    'first_name' => 'Elianna Amarah',
                    'middle_name' => 'Saucejo',
                    'last_name' => 'Divino',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000085',
                ],
                [
                    'first_name' => 'Althea Gwynne',
                    'middle_name' => 'Sabang',
                    'last_name' => 'Duro',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000086',
                ],
                [
                    'first_name' => 'Quinn Maize',
                    'middle_name' => 'Corsiga',
                    'last_name' => 'Jeda',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000087',
                ],
                [
                    'first_name' => 'Mika Cassandra',
                    'middle_name' => 'Lastimosa',
                    'last_name' => 'Lara',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000088',
                ],
                [
                    'first_name' => 'Johannah Cassandra',
                    'middle_name' => 'Aaron',
                    'last_name' => 'Melloria',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000089',
                ],
                [
                    'first_name' => 'Karina Anaiah',
                    'middle_name' => 'Remandaban',
                    'last_name' => 'Sepe',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000090',
                ],
                [
                    'first_name' => 'Angel Jade',
                    'middle_name' => 'D',
                    'last_name' => 'Tirol',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000091',
                ],
                [
                    'first_name' => 'Rose Ysabelle',
                    'middle_name' => 'Venturillo',
                    'last_name' => 'Torres',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000092',
                ],
                [
                    'first_name' => 'Kylie Amirah',
                    'middle_name' => 'Mascarinas',
                    'last_name' => 'Yung',
                    'grade_level' => '1',
                    'section' => 'St. Michael',
                    'gender' => 'Female',
                    'lrn' => '000000000093',
                ],

                /////////////////////////////////////////////////////////////////////////////////////
                // St. Joseph
                [
                    'first_name' => 'Klay Dylan',
                    'middle_name' => 'A',
                    'last_name' => 'Buligan',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Male',
                    'lrn' => '000000000094',
                ],
                [
                    'first_name' => 'Francis Gabriel',
                    'middle_name' => 'T',
                    'last_name' => 'Cumba',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Male',
                    'lrn' => '000000000095',
                ],
                [
                    'first_name' => 'Asher Ishmael',
                    'middle_name' => 'T',
                    'last_name' => 'Guishian',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Male',
                    'lrn' => '000000000096',
                ],
                [
                    'first_name' => 'Zayne Adriel',
                    'middle_name' => 'B',
                    'last_name' => 'Mata',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Male',
                    'lrn' => '000000000097',
                ],
                [
                    'first_name' => 'Luke Gibson',
                    'middle_name' => 'S',
                    'last_name' => 'Magana',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Male',
                    'lrn' => '000000000098',
                ],
                [
                    'first_name' => 'Adam Jem',
                    'middle_name' => 'O',
                    'last_name' => 'Morigo',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Male',
                    'lrn' => '000000000099',
                ],
                [
                    'first_name' => 'Jhumiko Fidel',
                    'middle_name' => 'V',
                    'last_name' => 'Rallos',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Male',
                    'lrn' => '000000000100',
                ],
                [
                    'first_name' => 'Galgrey Bron',
                    'middle_name' => 'M',
                    'last_name' => 'Ragay',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Male',
                    'lrn' => '000000000101',
                ],
                [
                    'first_name' => 'Joseiah Norman',
                    'middle_name' => 'B',
                    'last_name' => 'Solano',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Male',
                    'lrn' => '000000000102',
                ],
                [
                    'first_name' => 'Mike Alexander',
                    'middle_name' => 'C',
                    'last_name' => 'Recto',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Male',
                    'lrn' => '000000000103',
                ],
                [
                    'first_name' => 'Hezekiah Gabriel',
                    'middle_name' => 'B',
                    'last_name' => 'Torrefiel',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Male',
                    'lrn' => '000000000104',
                ],
                [
                    'first_name' => 'Arhea',
                    'middle_name' => 'L',
                    'last_name' => 'Abarquez',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000105',
                ],
                [
                    'first_name' => 'Cayleigh Jeane',
                    'middle_name' => 'M',
                    'last_name' => 'Joseph',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000106',
                ],
                [
                    'first_name' => 'Marianne Khate',
                    'middle_name' => 'T',
                    'last_name' => 'Lebita',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000107',
                ],
                [
                    'first_name' => 'Ma. Christine',
                    'middle_name' => 'G',
                    'last_name' => 'Jubahib',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000108',
                ],
                [
                    'first_name' => 'Jillian May',
                    'middle_name' => 'L',
                    'last_name' => 'Mante',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000109',
                ],
                [
                    'first_name' => 'Cyrah Elisse',
                    'middle_name' => 'B',
                    'last_name' => 'Mara',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000110',
                ],
                [
                    'first_name' => 'Stella Crisette',
                    'middle_name' => 'M',
                    'last_name' => 'Niones',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000111',
                ],
                [
                    'first_name' => 'Ahna Lyca Janzza',
                    'middle_name' => 'J',
                    'last_name' => 'Rebosura',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000112',
                ],
                [
                    'first_name' => 'Francine Ellise',
                    'middle_name' => 'M',
                    'last_name' => 'Remedio',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000113',
                ],
                [
                    'first_name' => 'Roni Alexios',
                    'middle_name' => 'C',
                    'last_name' => 'Salumbides',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000114',
                ],
                [
                    'first_name' => 'Quinn Adalee',
                    'middle_name' => 'E',
                    'last_name' => 'Sasil',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000115',
                ],
                [
                    'first_name' => 'Jennessy Saoirse',
                    'middle_name' => 'V',
                    'last_name' => 'Veloso',
                    'grade_level' => '1',
                    'section' => 'St. Joseph',
                    'gender' => 'Female',
                    'lrn' => '000000000116',
                ],

                /////////////////////////////////////////////////////////////////////////////////////
                // St. Anthony
                [
                    'first_name' => 'Steven Aziah',
                    'middle_name' => 'M',
                    'last_name' => 'Acaba',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000117',
                ],
                [
                    'first_name' => 'Steven',
                    'middle_name' => '',
                    'last_name' => 'Busalanan',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000118',
                ],
                [
                    'first_name' => 'Dane Nethaneel',
                    'middle_name' => 'C',
                    'last_name' => 'Cosare',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000119',
                ],
                [
                    'first_name' => 'Aebraham',
                    'middle_name' => 'D',
                    'last_name' => 'Dumangas',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000120',
                ],
                [
                    'first_name' => 'Mark Caeden',
                    'middle_name' => 'T',
                    'last_name' => 'Ediza',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000121',
                ],
                [
                    'first_name' => 'Kyrie Zane',
                    'middle_name' => 'L',
                    'last_name' => 'Fajardo',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000122',
                ],
                [
                    'first_name' => 'Caden Krij',
                    'middle_name' => 'D',
                    'last_name' => 'Gallego',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000123',
                ],
                [
                    'first_name' => 'Wiz Zylon',
                    'middle_name' => 'O',
                    'last_name' => 'Piezas',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000124',
                ],
                [
                    'first_name' => 'Ralph Nino',
                    'middle_name' => 'C',
                    'last_name' => 'Reserva',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000125',
                ],
                [
                    'first_name' => 'Yireh Miguel',
                    'middle_name' => 'M',
                    'last_name' => 'Revilla',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000126',
                ],
                [
                    'first_name' => 'Kris Jacob',
                    'middle_name' => 'E',
                    'last_name' => 'Ricafort',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000127',
                ],
                [
                    'first_name' => 'Kyrie Dayne',
                    'middle_name' => 'P',
                    'last_name' => 'Yumul',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Male',
                    'lrn' => '000000000128',
                ],
                [
                    'first_name' => 'Rheina',
                    'middle_name' => '',
                    'last_name' => 'Abella',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000129',
                ],
                [
                    'first_name' => 'Farah',
                    'middle_name' => 'L',
                    'last_name' => 'Asad',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000130',
                ],
                [
                    'first_name' => 'Ozella Audriana',
                    'middle_name' => 'C',
                    'last_name' => 'Bejer',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000131',
                ],
                [
                    'first_name' => 'Alliah Rein',
                    'middle_name' => 'N',
                    'last_name' => 'Betalzar',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000132',
                ],
                [
                    'first_name' => 'Ma. Liana Lyss',
                    'middle_name' => 'A',
                    'last_name' => 'Calago',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000133',
                ],
                [
                    'first_name' => 'Mikaela',
                    'middle_name' => '',
                    'last_name' => 'Corbeta',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000134',
                ],
                [
                    'first_name' => 'Nazel Juliana',
                    'middle_name' => 'T',
                    'last_name' => 'Diacor',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000135',
                ],
                [
                    'first_name' => 'Savana',
                    'middle_name' => 'S',
                    'last_name' => 'Estepa',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000136',
                ],
                [
                    'first_name' => 'Chesca Ysabella',
                    'middle_name' => 'T',
                    'last_name' => 'Flores',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000137',
                ],
                [
                    'first_name' => 'Mikaela',
                    'middle_name' => 'M',
                    'last_name' => 'Lasay',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000138',
                ],
                [
                    'first_name' => 'Janiah Priette',
                    'middle_name' => 'D',
                    'last_name' => 'Nazareno',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000139',
                ],
                [
                    'first_name' => 'Cheyenne',
                    'middle_name' => 'C',
                    'last_name' => 'Phillips',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000140',
                ],
                [
                    'first_name' => 'Kaitlin Avery',
                    'middle_name' => 'T',
                    'last_name' => 'Ramos',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000141',
                ],
                [
                    'first_name' => 'Moira Anette',
                    'middle_name' => 'D',
                    'last_name' => 'Sanico',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000142',
                ],
                [
                    'first_name' => 'Zara Allyson',
                    'middle_name' => 'T',
                    'last_name' => 'Silagan',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000143',
                ],
                [
                    'first_name' => 'Lilian Joezeth',
                    'middle_name' => 'R',
                    'last_name' => 'Tuquib',
                    'grade_level' => '4',
                    'section' => 'St. Anthony',
                    'gender' => 'Female',
                    'lrn' => '000000000144',
                ],

                /////////////////////////////////////////////////////////////////////////////////////
                // St. Luke
                [
                    'first_name' => 'Hezekiah Barry',
                    'middle_name' => 'C',
                    'last_name' => 'Abarquez',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000145',
                ],
                [
                    'first_name' => 'Josh Niño',
                    'middle_name' => 'R',
                    'last_name' => 'Ando',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000146',
                ],
                [
                    'first_name' => 'Zach Franco',
                    'middle_name' => 'G',
                    'last_name' => 'Añedez',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000147',
                ],
                [
                    'first_name' => 'Elli Zander',
                    'middle_name' => 'B',
                    'last_name' => 'Baruc',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000148',
                ],
                [
                    'first_name' => 'Rigel Kent',
                    'middle_name' => 'O',
                    'last_name' => 'Cabaluna',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000149',
                ],
                [
                    'first_name' => 'Mark Andrei',
                    'middle_name' => 'M',
                    'last_name' => 'Capablanca',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000150',
                ],
                [
                    'first_name' => 'Reef Dmitri',
                    'middle_name' => 'C',
                    'last_name' => 'Cua',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000151',
                ],
                [
                    'first_name' => 'Izeguel',
                    'middle_name' => 'C',
                    'last_name' => 'Deliosa',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000152',
                ],
                [
                    'first_name' => 'Edyn Zustin Siph Marie',
                    'middle_name' => 'D',
                    'last_name' => 'Inocian',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000153',
                ],
                [
                    'first_name' => 'AJ Xyriel',
                    'middle_name' => 'R',
                    'last_name' => 'Jalawiq',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000154',
                ],
                [
                    'first_name' => 'John Stephen',
                    'middle_name' => 'R',
                    'last_name' => 'Lanoy',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000155',
                ],
                [
                    'first_name' => 'Prince Rudy',
                    'middle_name' => 'B',
                    'last_name' => 'Lebita',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000156',
                ],
                [
                    'first_name' => 'Gab Ezekiel',
                    'middle_name' => 'G',
                    'last_name' => 'Leyson',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000157',
                ],
                [
                    'first_name' => 'Gabriel Adam',
                    'middle_name' => 'O',
                    'last_name' => 'Man-On',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000158',
                ],
                [
                    'first_name' => 'Zane Adrian',
                    'middle_name' => 'J',
                    'last_name' => 'Rible',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000159',
                ],
                [
                    'first_name' => 'Xander Graye',
                    'middle_name' => 'M',
                    'last_name' => 'Tupas',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000160',
                ],
                [
                    'first_name' => 'Samuel Luigi',
                    'middle_name' => 'B',
                    'last_name' => 'Tupaz',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Male',
                    'lrn' => '000000000161',
                ],
                [
                    'first_name' => 'Joanna Mae',
                    'middle_name' => 'C',
                    'last_name' => 'Abello',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000162',
                ],
                [
                    'first_name' => 'Caeli Alexa',
                    'middle_name' => 'L',
                    'last_name' => 'Alcancia',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000163',
                ],
                [
                    'first_name' => 'Athena Josephine',
                    'middle_name' => 'A',
                    'last_name' => 'Apare',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000164',
                ],
                [
                    'first_name' => 'Isabella Dreama',
                    'middle_name' => '',
                    'last_name' => 'Apolonias',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000165',
                ],
                [
                    'first_name' => 'Sommer',
                    'middle_name' => 'V',
                    'last_name' => 'Dinoy',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000166',
                ],
                [
                    'first_name' => 'Zahra Skye',
                    'middle_name' => 'B',
                    'last_name' => 'Edmonds',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000167',
                ],
                [
                    'first_name' => 'Azriela Maryam',
                    'middle_name' => 'L',
                    'last_name' => 'Escalderon',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000168',
                ],
                [
                    'first_name' => 'Chrys Gianah',
                    'middle_name' => 'L',
                    'last_name' => 'Lauron',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000169',
                ],
                [
                    'first_name' => 'Glean Eliza',
                    'middle_name' => 'B',
                    'last_name' => 'Legario',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000170',
                ],
                [
                    'first_name' => 'Leah Rose',
                    'middle_name' => 'T',
                    'last_name' => 'Lofranco',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000171',
                ],
                [
                    'first_name' => 'Gibeah Cayenne',
                    'middle_name' => 'J',
                    'last_name' => 'Poquita',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000172',
                ],
                [
                    'first_name' => 'Ma. Galyi Anne',
                    'middle_name' => 'J',
                    'last_name' => 'Rebosura',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000173',
                ],
                [
                    'first_name' => 'Nash Carla',
                    'middle_name' => 'S',
                    'last_name' => 'Remedio',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000174',
                ],
                [
                    'first_name' => 'Kaily Xavinika',
                    'middle_name' => 'R',
                    'last_name' => 'Sepe',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000175',
                ],
                [
                    'first_name' => 'Carily Marie',
                    'middle_name' => 'R',
                    'last_name' => 'Urbien',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000176',
                ],
                [
                    'first_name' => 'Yuri Cassidy',
                    'middle_name' => 'T',
                    'last_name' => 'Youn',
                    'grade_level' => '3',
                    'section' => 'St. Luke',
                    'gender' => 'Female',
                    'lrn' => '000000000177',
                ],

                /////////////////////////////////////////////////////////////////////////////////////
                // St. Benedict
                [
                    'first_name' => 'Zane',
                    'middle_name' => 'Lopez',
                    'last_name' => 'Anunciado',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Male',
                    'lrn' => '000000000178',
                ],
                [
                    'first_name' => 'Matt Benedict',
                    'middle_name' => 'Torretalma',
                    'last_name' => 'Capablanca',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Male',
                    'lrn' => '000000000179',
                ],
                [
                    'first_name' => 'Christian Rey',
                    'middle_name' => 'Rodriguez',
                    'last_name' => 'Gionson',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Male',
                    'lrn' => '000000000180',
                ],
                [
                    'first_name' => 'Keevin Myr',
                    'middle_name' => 'Guiliat',
                    'last_name' => 'Lamarillao',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Male',
                    'lrn' => '000000000181',
                ],
                [
                    'first_name' => 'Liam',
                    'middle_name' => 'Gecera',
                    'last_name' => 'Lauron',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Male',
                    'lrn' => '000000000182',
                ],
                [
                    'first_name' => 'Alexander Ramon',
                    'middle_name' => 'Lebita',
                    'last_name' => 'Mabanag',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Male',
                    'lrn' => '000000000183',
                ],
                [
                    'first_name' => 'Kyrie Eleison',
                    'middle_name' => 'Cajes',
                    'last_name' => 'Manigo',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Male',
                    'lrn' => '000000000184',
                ],
                [
                    'first_name' => 'Ritz Jhon II',
                    'middle_name' => 'Enriquez',
                    'last_name' => 'Piezas',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Male',
                    'lrn' => '000000000185',
                ],
                [
                    'first_name' => 'Ezekiel Vince',
                    'middle_name' => 'Gucor',
                    'last_name' => 'Quibol',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Male',
                    'lrn' => '000000000186',
                ],
                [
                    'first_name' => 'Jorhe Zemen',
                    'middle_name' => 'Pajuleras',
                    'last_name' => 'Rotoras',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Male',
                    'lrn' => '000000000187',
                ],
                [
                    'first_name' => 'Rue Arkyel',
                    'middle_name' => 'Colegado',
                    'last_name' => 'Tapayan',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Male',
                    'lrn' => '000000000188',
                ],
                [
                    'first_name' => 'Yvie Dominique',
                    'middle_name' => 'Melicor',
                    'last_name' => 'Abella',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000189',
                ],
                [
                    'first_name' => 'Thyline Zayn',
                    'middle_name' => 'Lagurin',
                    'last_name' => 'Algusar',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000190',
                ],
                [
                    'first_name' => 'Kisha',
                    'middle_name' => 'Bustalinio',
                    'last_name' => 'Aspe',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000191',
                ],
                [
                    'first_name' => 'Jandy Marie',
                    'middle_name' => 'Balorio',
                    'last_name' => 'Balat',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000192',
                ],
                [
                    'first_name' => 'Zoey Riley',
                    'middle_name' => 'Ricafort',
                    'last_name' => 'Canizares',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000193',
                ],
                [
                    'first_name' => 'Thaleya',
                    'middle_name' => 'Vano',
                    'last_name' => 'Celades',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000194',
                ],
                [
                    'first_name' => 'Minara Germaine',
                    'middle_name' => 'Yare',
                    'last_name' => 'Curib',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000195',
                ],
                [
                    'first_name' => 'Danielia Claire',
                    'middle_name' => 'Boligao',
                    'last_name' => 'Encabo',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000196',
                ],
                [
                    'first_name' => 'Ayah Martina',
                    'middle_name' => 'Sab',
                    'last_name' => 'Gastanes',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000197',
                ],
                [
                    'first_name' => 'Hyomi Sky',
                    'middle_name' => 'Argamosa',
                    'last_name' => 'Lagapa',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000198',
                ],
                [
                    'first_name' => 'Janna Jay',
                    'middle_name' => 'D',
                    'last_name' => 'Lebita',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000199',
                ],
                [
                    'first_name' => 'Maddison Rose',
                    'middle_name' => 'Arii',
                    'last_name' => 'Lerion',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000200',
                ],
                [
                    'first_name' => 'Zoey Gayle',
                    'middle_name' => 'Pacanza',
                    'last_name' => 'Millanar',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000201',
                ],
                [
                    'first_name' => 'Ye On',
                    'middle_name' => 'Piezas',
                    'last_name' => 'Moon',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000202',
                ],
                [
                    'first_name' => 'Shaiya Abish',
                    'middle_name' => 'Rosario',
                    'last_name' => 'Samputon',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000203',
                ],
                [
                    'first_name' => 'Cassandra Alaine',
                    'middle_name' => 'Genabia',
                    'last_name' => 'Siga',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000204',
                ],
                [
                    'first_name' => 'Khelia Athena',
                    'middle_name' => 'Sepe',
                    'last_name' => 'Talaboc',
                    'grade_level' => '5',
                    'section' => 'St. Benedict',
                    'gender' => 'Female',
                    'lrn' => '000000000205',
                ],
                /////////////////////////////////////////////////////////////////////////////////////
        ];

        $usedLrns = [];
        $successfulStudents = 0;
        $failedStudents = 0;

        // Create Parents and Students based on actual data
        foreach ($studentsData as $index => $studentData) {
            $parentNumber = $index + 1;
            
            // Validate if the grade level exists
            if (!array_key_exists($studentData['grade_level'], $gradeSections)) {
                $this->command->error("Invalid grade level '{$studentData['grade_level']}'. Available grade levels: " . implode(', ', array_keys($gradeSections)));
                $failedStudents++;
                continue;
            }

            // Validate if the section is valid for the grade level
            if (!in_array($studentData['section'], $gradeSections[$studentData['grade_level']])) {
                $validSections = implode(', ', $gradeSections[$studentData['grade_level']]);
                $this->command->error("Invalid section '{$studentData['section']}' for grade level '{$studentData['grade_level']}'. Valid sections: {$validSections}");
                $failedStudents++;
                continue;
            }

            // Generate unique email
            $lastNameClean = preg_replace('/[^a-zA-Z0-9]/', '', $studentData['last_name']);

            // Get only the first word of the first name (full word, not shortened)
            $firstNameParts = explode(' ', $studentData['first_name']);
            $firstWord = $firstNameParts[0];
            $firstNameClean = preg_replace('/[^a-zA-Z0-9]/', '', $firstWord);

            $baseEmail = strtolower("{$lastNameClean}_{$firstNameClean}@example.com");
            $email = $baseEmail;
            $counter = 1;

            while (User::where('email', $email)->exists()) {
                $email = strtolower("{$lastNameClean}_{$firstNameClean}{$counter}@example.com");
                $counter++;
            }

            $parent = User::create([
                'name' => "Parent {$studentData['last_name']}",
                'email' => $email,
                'password' => Hash::make('password_2025'),
            ]);
            $parent->assignRole('parent');

            // Find the class based on grade level and section
            $class = ClassModel::where('grade_level', $studentData['grade_level'])
                              ->where('name', $studentData['section'])
                              ->first();

            if (!$class) {
                $this->command->error("Class not found for grade {$studentData['grade_level']} section {$studentData['section']}. Skipping student {$studentData['first_name']} {$studentData['last_name']}");
                $failedStudents++;
                continue;
            }

            // Check for duplicate LRN
            if (in_array($studentData['lrn'], $usedLrns)) {
                $this->command->error("Duplicate LRN {$studentData['lrn']} for student {$studentData['first_name']} {$studentData['last_name']}. Skipping.");
                $failedStudents++;
                continue;
            }
            $usedLrns[] = $studentData['lrn'];

            // Create student
            $student = Student::create([
                'first_name' => $studentData['first_name'],
                'middle_name' => $studentData['middle_name'],
                'last_name' => $studentData['last_name'],
                'class_id' => $class->id,
                'parent_id' => $parent->id,
                'approved_by_teacher' => true,
                'lrn' => $studentData['lrn'],
                'gender' => $studentData['gender'],
            ]);

            $this->command->info("✓ Created student: {$studentData['first_name']} {$studentData['last_name']} in Grade {$studentData['grade_level']} - {$studentData['section']}");
            $successfulStudents++;
        }

        $this->command->info("\nSeeder Summary:");
        $this->command->info("Successfully created: {$successfulStudents} students with parent accounts");
        $this->command->info("Failed: {$failedStudents} students");
        $this->command->info("No grades were automatically generated. Add grades manually as needed.");
    }
}