<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Parent Accounts Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #333; }
        .header p { margin: 5px 0; color: #666; }
        .table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .table th { background-color: #f5f5f5; font-weight: bold; }
        .info-section { margin-bottom: 20px; }
        .info-section p { margin: 5px 0; }
        .no-data { text-align: center; color: #666; font-style: italic; padding: 20px; }
        .student-list { margin: 0; padding-left: 15px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Parent Accounts Report</h1>
        <p>Generated on: {{ $generated_date }}</p>
        @if($selected_class)
            <p>Class: {{ $selected_class->name }} (Grade {{ $selected_class->grade_level }})</p>
        @else
            <p>Class: All Classes</p>
        @endif
        <p>Generated by: {{ $teacher->name }}</p>
    </div>

    <div class="info-section">
        <p><strong>Total Parents:</strong> {{ $parents->count() }}</p>
    </div>

    @if($parents->count() > 0)
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Parent Name</th>
                    <th>Email</th>
                    <th>Password</th>
                    <th>Status</th>
                    <th>Students</th>
                </tr>
            </thead>
            <tbody>
                @foreach($parents as $index => $parent)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $parent->name }}</td>
                        <td>{{ $parent->email }}</td>
                        <td><strong>{{ $parent->generated_password ?? 'N/A' }}</strong></td>
                        <td>
                            <span style="color: {{ $parent->status === 'active' ? 'green' : 'red' }}; font-weight: bold;">
                                {{ ucfirst($parent->status) }}
                            </span>
                        </td>
                        <td>
                            @if($parent->students && $parent->students->count() > 0)
                                <ul class="student-list">
                                    @foreach($parent->students as $student)
                                        <li>{{ $student->first_name }} {{ $student->middle_name }} {{ $student->last_name }}</li>
                                    @endforeach
                                </ul>
                            @else
                                <span style="color: #666; font-style: italic;">No students assigned</span>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">
            <p>No parent accounts found for the selected criteria.</p>
        </div>
    @endif

    <div style="margin-top: 30px; text-align: center; color: #666; font-size: 12px;">
        <p>Report generated by {{ config('app.name') }} - {{ $generated_date }}</p>
    </div>
</body>
</html>